FROM python:3.6-slim

# Install Jupyter
RUN pip install jupyter

RUN pip --no-cache-dir install \
        Pillow \
        jupyter \
        matplotlib \
        numpy \
        pandas \
        scipy \
        sklearn

RUN buildDeps=' \
	build-essential \
	libxml2-dev \
	zlib1g-dev
	' \
	&& apt-get update && apt-get install -y $buildDeps --no-install-recommends \
	&& rm -rf /var/lib/apt/lists/* \
	&& apt-get purge -y --auto-remove $buildDeps \


# Jupyter has issues with being run directly:
#   https://github.com/ipython/ipython/issues/7062
# We just add a little wrapper script.
COPY run_jupyter.sh /
COPY jupyter_notebook_config.py /root/.jupyter/

# Jupyter
EXPOSE 8888

CMD ["/run_jupyter.sh", "--allow-root"]
