FROM python:3.6-slim

RUN buildDeps=' \
	build-essential \
	libxml2-dev \
	zlib1g-dev \
	python-dev \
	pkg-config \
	libffi-dev \
	libcairo-dev \
	' \
	&& apt-get update && apt-get install -y $buildDeps --no-install-recommends

## this command makes python3.4 worse
# RUN apt-get install -y python3-cairo

# pip install
RUN pip --no-cache-dir install \
        Pillow \
        jupyter \
        matplotlib \
        numpy \
        pandas \
        scipy \
        sklearn \
	python-igraph \
	cairocffi

RUN rm -rf /var/lib/apt/lists/* \
	&& apt-get purge -y --auto-remove $buildDeps

# Jupyter has issues with being run directly:
#   https://github.com/ipython/ipython/issues/7062
# We just add a little wrapper script.
COPY run_jupyter.sh /
COPY jupyter_notebook_config.py /root/.jupyter/

# Jupyter
EXPOSE 8888

CMD ["/run_jupyter.sh", "--allow-root"]
