FROM pytorch:0.3

RUN pip --no-cache-dir install \
	jupyter \
	matplotlib \
	torchvision \
	torchtext 

# Jupyter has issues with being run directly:
#   https://github.com/ipython/ipython/issues/7062
# We just add a little wrapper script.
COPY run_jupyter.sh /
COPY jupyter_notebook_config.py /root/.jupyter/

# Jupyter
EXPOSE 8888

CMD ["/run_jupyter.sh"]
